### ISSUE TITLE
Doesn't seem to work on 1.21

### ISSUE THREAD

**Issue by maksiksking** [Felix14-v2/Loyal-Items#2]
Doesn't work on my 1.21 server

**Comment by Felix14-v2** [comment]
Can you provide more technical info? I'll try to reproduce

**Comment by Felix14-v2** [comment]
Ah, nevermind, Mojang just broke all the datapacks... I'll publish a new release soon. You can just rename `functions` and `advancements` folders to `function` and `advancement` to fix that.

**Comment by maksiksking** [comment]
Mojang is being funny and not considering a big community with its internal changes as always... Anyway, fixed it and made a pull request so you don't have to fix anything. Check if it works with /tick sprint first though just in case.

**Comment by Felix14-v2** [comment]
Actually I appreciate their work, their changes are quite important for optimizing and improving the game. I already updated (and backported) the pack, so this can be closed.
