### ISSUE TITLE
Server crash after updating to v1.0.1

### ISSUE THREAD

**Issue by denny4-user** [Felix14-v2/Loyal-Items#6]
It was like this, at first my Forge 1.19.2 server had v1.0.0 - then I decided to reinstall it to v1.0.1 and this crash happened, here is the log:
Additionally: there are no items in the world that are protected from despawn
[c.txt](https://github.com/user-attachments/files/16229286/c.txt)

**Comment by Felix14-v2** [comment]
Oh, wrong metadata... Thanks for letting me know, I'll fix that when I get home. Sorry for inconvenience!

**Comment by Felix14-v2** [comment]
Fixed! If you find any other issues, feel free to report them.
